CREATE TABLE IF NOT EXISTS rate_limit_windows (
  key TEXT PRIMARY KEY CHECK (length(key) BETWEEN 1 AND 512),
  request_count BIGINT NOT NULL CHECK (request_count > 0),
  resets_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS rate_limit_windows_expiry
  ON rate_limit_windows(resets_at);

CREATE TABLE IF NOT EXISTS organizations (
  id TEXT PRIMARY KEY CHECK (length(id) BETWEEN 1 AND 128),
  auth0_org_id TEXT NOT NULL UNIQUE CHECK (length(auth0_org_id) BETWEEN 1 AND 128),
  name TEXT NOT NULL CHECK (length(name) BETWEEN 1 AND 200),
  kind TEXT NOT NULL CHECK (kind IN ('buyer', 'supplier')),
  stripe_customer_id TEXT UNIQUE
    CHECK (stripe_customer_id IS NULL OR length(stripe_customer_id) BETWEEN 1 AND 128),
  created_at TEXT NOT NULL
    DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
    CHECK (created_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$')
);

CREATE TABLE IF NOT EXISTS wallet_accounts (
  organization_id TEXT PRIMARY KEY,
  currency TEXT NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
  balance BIGINT NOT NULL DEFAULT 0 CHECK (balance BETWEEN 0 AND 10000000000),
  created_at TEXT NOT NULL CHECK (
    created_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'
  ),
  updated_at TEXT NOT NULL CHECK (
    updated_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'
    AND updated_at >= created_at
  ),
  FOREIGN KEY (organization_id)
    REFERENCES organizations(id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS wallet_topups (
  id TEXT PRIMARY KEY CHECK (length(id) = 36),
  organization_id TEXT NOT NULL,
  amount BIGINT NOT NULL CHECK (amount BETWEEN 100 AND 100000000),
  currency TEXT NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
  status TEXT NOT NULL CHECK (status IN ('pending', 'paid', 'failed')),
  stripe_payment_intent_id TEXT UNIQUE
    CHECK (stripe_payment_intent_id IS NULL OR length(stripe_payment_intent_id) BETWEEN 1 AND 128),
  created_at TEXT NOT NULL CHECK (
    created_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'
  ),
  updated_at TEXT NOT NULL CHECK (
    updated_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'
    AND updated_at >= created_at
  ),
  FOREIGN KEY (organization_id)
    REFERENCES organizations(id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS wallet_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('funding', 'purchase')),
  amount BIGINT NOT NULL CHECK (amount BETWEEN 1 AND 100000000),
  order_id TEXT UNIQUE,
  stripe_payment_intent_id TEXT UNIQUE,
  created_at TEXT NOT NULL CHECK (
    created_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'
  ),
  CHECK (
    (kind = 'funding' AND stripe_payment_intent_id IS NOT NULL AND order_id IS NULL)
    OR (kind = 'purchase' AND order_id IS NOT NULL AND stripe_payment_intent_id IS NULL)
  ),
  FOREIGN KEY (organization_id)
    REFERENCES organizations(id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS catalog_items (
  id TEXT PRIMARY KEY CHECK (length(id) BETWEEN 1 AND 128),
  supplier_organization_id TEXT NOT NULL,
  sku TEXT NOT NULL CHECK (length(sku) BETWEEN 1 AND 128),
  product_key TEXT NOT NULL CHECK (length(product_key) BETWEEN 1 AND 128),
  category TEXT NOT NULL CHECK (length(category) BETWEEN 1 AND 128),
  unit TEXT NOT NULL CHECK (length(unit) BETWEEN 1 AND 64),
  unit_price BIGINT NOT NULL CHECK (unit_price BETWEEN 1 AND 10000000000),
  currency TEXT NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
  advisory_quantity INTEGER NOT NULL
    CHECK (advisory_quantity BETWEEN 0 AND 1000000),
  valid_from TEXT NOT NULL
    CHECK (valid_from ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'),
  valid_until TEXT NOT NULL CHECK (
    valid_until ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'
    AND valid_until > valid_from
  ),
  display_name TEXT NOT NULL CHECK (length(display_name) BETWEEN 1 AND 200),
  description TEXT CHECK (description IS NULL OR length(description) <= 2000),
  active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
  version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
  created_at TEXT NOT NULL
    DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
    CHECK (created_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'),
  updated_at TEXT NOT NULL
    DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
    CHECK (
      updated_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'
      AND updated_at >= created_at
    ),
  UNIQUE (supplier_organization_id, sku),
  UNIQUE (id, supplier_organization_id),
  FOREIGN KEY (supplier_organization_id)
    REFERENCES organizations(id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS catalog_items_offer_lookup
  ON catalog_items(product_key, unit, active, valid_until, unit_price, supplier_organization_id);

CREATE TABLE IF NOT EXISTS mandates (
  id TEXT PRIMARY KEY CHECK (length(id) BETWEEN 1 AND 128),
  buyer_organization_id TEXT NOT NULL,
  version INTEGER NOT NULL CHECK (version >= 1),
  state TEXT NOT NULL CHECK (state IN ('active', 'superseded', 'revoked')),
  valid_from TEXT NOT NULL
    CHECK (valid_from ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'),
  valid_until TEXT NOT NULL CHECK (
    valid_until ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'
    AND valid_until > valid_from
  ),
  policy_json TEXT NOT NULL
    CHECK (jsonb_typeof(policy_json::jsonb) = 'object'),
  schema_version INTEGER NOT NULL CHECK (schema_version >= 1),
  policy_hash TEXT NOT NULL CHECK (policy_hash ~ '^[0-9a-f]{64}$'),
  created_by_subject TEXT NOT NULL
    CHECK (length(created_by_subject) BETWEEN 1 AND 256),
  created_at TEXT NOT NULL
    DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
    CHECK (created_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'),
  UNIQUE (buyer_organization_id, version),
  UNIQUE (id, buyer_organization_id, version, policy_hash),
  FOREIGN KEY (buyer_organization_id)
    REFERENCES organizations(id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS mandates_one_active_per_buyer
  ON mandates(buyer_organization_id)
  WHERE state = 'active';

CREATE TABLE IF NOT EXISTS order_denials (
  buyer_organization_id TEXT NOT NULL,
  requester_subject TEXT NOT NULL
    CHECK (length(requester_subject) BETWEEN 1 AND 256),
  idempotency_key TEXT NOT NULL CHECK (length(idempotency_key) = 36),
  request_hash TEXT NOT NULL CHECK (request_hash ~ '^[0-9a-f]{64}$'),
  policy_reasons_json TEXT NOT NULL
    CHECK (jsonb_typeof(policy_reasons_json::jsonb) = 'array'),
  created_at TEXT NOT NULL
    CHECK (created_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'),
  PRIMARY KEY (
    buyer_organization_id,
    requester_subject,
    idempotency_key
  ),
  FOREIGN KEY (buyer_organization_id)
    REFERENCES organizations(id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY CHECK (length(id) BETWEEN 1 AND 128),
  buyer_organization_id TEXT NOT NULL,
  supplier_organization_id TEXT NOT NULL,
  requester_subject TEXT NOT NULL
    CHECK (length(requester_subject) BETWEEN 1 AND 256),
  mandate_id TEXT NOT NULL,
  mandate_version INTEGER NOT NULL CHECK (mandate_version >= 1),
  mandate_hash TEXT NOT NULL CHECK (mandate_hash ~ '^[0-9a-f]{64}$'),
  catalog_item_id TEXT NOT NULL,
  catalog_item_version INTEGER NOT NULL CHECK (catalog_item_version >= 1),
  sku TEXT NOT NULL CHECK (length(sku) BETWEEN 1 AND 128),
  product_key TEXT NOT NULL CHECK (length(product_key) BETWEEN 1 AND 128),
  category TEXT NOT NULL CHECK (length(category) BETWEEN 1 AND 128),
  unit TEXT NOT NULL CHECK (length(unit) BETWEEN 1 AND 64),
  unit_price BIGINT NOT NULL CHECK (unit_price BETWEEN 1 AND 10000000000),
  quantity INTEGER NOT NULL CHECK (quantity BETWEEN 1 AND 1000000),
  currency TEXT NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
  total BIGINT NOT NULL CHECK (
    total BETWEEN 1 AND 10000000000
    AND unit_price <= 10000000000 / quantity
    AND total = unit_price * quantity
  ),
  delivery_location_id TEXT NOT NULL
    CHECK (length(delivery_location_id) BETWEEN 1 AND 128),
  status TEXT NOT NULL CHECK (status IN (
    'denied',
    'awaiting_approval',
    'payment_pending',
    'paid',
    'payment_failed',
    'rejected',
    'stale',
    'expired',
    'cancelled'
  )),
  policy_decision TEXT NOT NULL
    CHECK (policy_decision IN ('allow', 'require_approval', 'deny')),
  policy_reasons_json TEXT NOT NULL
    CHECK (jsonb_typeof(policy_reasons_json::jsonb) = 'array'),
  idempotency_key TEXT NOT NULL CHECK (length(idempotency_key) = 36),
  request_hash TEXT NOT NULL CHECK (request_hash ~ '^[0-9a-f]{64}$'),
  approval_expires_at TEXT CHECK (
    approval_expires_at IS NULL
    OR (
      approval_expires_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'
      AND approval_expires_at > created_at
    )
  ),
  approval_actor_subject TEXT
    CHECK (approval_actor_subject IS NULL OR length(approval_actor_subject) BETWEEN 1 AND 256),
  approval_decided_at TEXT CHECK (
    approval_decided_at IS NULL
    OR approval_decided_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'
  ),
  approval_reason TEXT CHECK (approval_reason IS NULL OR length(approval_reason) <= 1000),
  stripe_create_started_at TEXT CHECK (
    stripe_create_started_at IS NULL
    OR stripe_create_started_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'
  ),
  stripe_payment_intent_id TEXT UNIQUE CHECK (
    stripe_payment_intent_id IS NULL
    OR length(stripe_payment_intent_id) BETWEEN 1 AND 128
  ),
  wallet_paid_at TEXT CHECK (
    wallet_paid_at IS NULL
    OR wallet_paid_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'
  ),
  created_at TEXT NOT NULL
    DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
    CHECK (created_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'),
  updated_at TEXT NOT NULL
    DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
    CHECK (
      updated_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'
      AND updated_at >= created_at
    ),
  UNIQUE (buyer_organization_id, requester_subject, idempotency_key),
  CHECK (buyer_organization_id <> supplier_organization_id),
  CHECK (
    (policy_decision = 'deny' AND status = 'denied')
    OR (
      policy_decision = 'allow'
      AND status IN ('payment_pending', 'paid', 'payment_failed', 'cancelled')
    )
    OR (
      policy_decision = 'require_approval'
      AND status IN (
        'awaiting_approval',
        'payment_pending',
        'paid',
        'payment_failed',
        'rejected',
        'stale',
        'expired',
        'cancelled'
      )
    )
  ),
  CHECK (
    (policy_decision = 'require_approval' AND approval_expires_at IS NOT NULL)
    OR (policy_decision <> 'require_approval' AND approval_expires_at IS NULL)
  ),
  CHECK (
    (approval_actor_subject IS NULL AND approval_decided_at IS NULL)
    OR (approval_actor_subject IS NOT NULL AND approval_decided_at IS NOT NULL)
  ),
  CHECK (approval_reason IS NULL OR approval_actor_subject IS NOT NULL),
  CHECK (
    policy_decision = 'require_approval'
    OR (
      approval_actor_subject IS NULL
      AND approval_decided_at IS NULL
      AND approval_reason IS NULL
    )
  ),
  CHECK (
    policy_decision <> 'require_approval'
    OR status IN ('awaiting_approval', 'stale', 'expired')
    OR approval_actor_subject IS NOT NULL
  ),
  CHECK (
    stripe_create_started_at IS NULL
    OR status IN ('payment_pending', 'paid', 'payment_failed', 'cancelled')
  ),
  CHECK (
    stripe_payment_intent_id IS NULL
    OR (
      stripe_create_started_at IS NOT NULL
      AND status IN ('payment_pending', 'paid', 'payment_failed', 'cancelled')
    )
  ),
  CHECK (
    status NOT IN ('paid', 'payment_failed')
    OR stripe_payment_intent_id IS NOT NULL
    OR (status = 'paid' AND wallet_paid_at IS NOT NULL)
  ),
  CHECK (
    wallet_paid_at IS NULL
    OR (status = 'paid' AND stripe_payment_intent_id IS NULL)
  ),
  FOREIGN KEY (mandate_id, buyer_organization_id, mandate_version, mandate_hash)
    REFERENCES mandates(id, buyer_organization_id, version, policy_hash)
    ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (catalog_item_id, supplier_organization_id)
    REFERENCES catalog_items(id, supplier_organization_id)
    ON UPDATE RESTRICT ON DELETE RESTRICT
);

ALTER TABLE orders ADD COLUMN IF NOT EXISTS wallet_paid_at TEXT;
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_check12;
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_paid_source_check;
ALTER TABLE orders ADD CONSTRAINT orders_paid_source_check CHECK (
  status NOT IN ('paid', 'payment_failed')
  OR stripe_payment_intent_id IS NOT NULL
  OR (status = 'paid' AND wallet_paid_at IS NOT NULL)
);
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_wallet_source_check;
ALTER TABLE orders ADD CONSTRAINT orders_wallet_source_check CHECK (
  wallet_paid_at IS NULL
  OR (
    wallet_paid_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'
    AND status = 'paid'
    AND stripe_payment_intent_id IS NULL
  )
);

CREATE INDEX IF NOT EXISTS orders_buyer_status
  ON orders(buyer_organization_id, status, created_at);

CREATE INDEX IF NOT EXISTS orders_supplier_status
  ON orders(supplier_organization_id, status, created_at);

CREATE INDEX IF NOT EXISTS orders_pending_approvals
  ON orders(buyer_organization_id, approval_expires_at)
  WHERE status = 'awaiting_approval';

CREATE TABLE IF NOT EXISTS stripe_events (
  event_id TEXT PRIMARY KEY CHECK (length(event_id) BETWEEN 1 AND 128),
  type TEXT NOT NULL CHECK (length(type) BETWEEN 1 AND 128),
  object_id TEXT NOT NULL CHECK (length(object_id) BETWEEN 1 AND 128),
  received_at TEXT NOT NULL
    DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
    CHECK (received_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'),
  processed_at TEXT CHECK (
    processed_at IS NULL
    OR (
      processed_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'
      AND processed_at >= received_at
    )
  )
);

CREATE INDEX IF NOT EXISTS stripe_events_object
  ON stripe_events(object_id, received_at);

CREATE TABLE IF NOT EXISTS audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aggregate_type TEXT NOT NULL CHECK (length(aggregate_type) BETWEEN 1 AND 64),
  aggregate_id TEXT NOT NULL CHECK (length(aggregate_id) BETWEEN 1 AND 128),
  organization_id TEXT,
  event_type TEXT NOT NULL CHECK (length(event_type) BETWEEN 1 AND 128),
  actor_type TEXT NOT NULL CHECK (
    actor_type IN ('buyer_agent', 'supplier_agent', 'human', 'system', 'stripe', 'anonymous')
  ),
  actor_subject TEXT
    CHECK (actor_subject IS NULL OR length(actor_subject) BETWEEN 1 AND 256),
  request_id TEXT NOT NULL CHECK (length(request_id) BETWEEN 1 AND 128),
  payload_json TEXT NOT NULL
    CHECK (jsonb_typeof(payload_json::jsonb) = 'object'),
  created_at TEXT NOT NULL
    DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
    CHECK (created_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*Z$'),
  FOREIGN KEY (organization_id)
    REFERENCES organizations(id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS audit_events_organization_time
  ON audit_events(organization_id, created_at, id);

CREATE INDEX IF NOT EXISTS audit_events_aggregate
  ON audit_events(aggregate_type, aggregate_id, created_at, id);

CREATE OR REPLACE FUNCTION reject_mandate_immutable_update()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF ROW(
    NEW.id, NEW.buyer_organization_id, NEW.version, NEW.valid_from,
    NEW.valid_until, NEW.policy_json, NEW.schema_version, NEW.policy_hash,
    NEW.created_by_subject, NEW.created_at
  ) IS DISTINCT FROM ROW(
    OLD.id, OLD.buyer_organization_id, OLD.version, OLD.valid_from,
    OLD.valid_until, OLD.policy_json, OLD.schema_version, OLD.policy_hash,
    OLD.created_by_subject, OLD.created_at
  ) THEN
    RAISE EXCEPTION 'mandate versions are immutable';
  END IF;
  IF NEW.state IS DISTINCT FROM OLD.state
    AND NOT (
      OLD.state = 'active'
      AND NEW.state IN ('superseded', 'revoked')
    )
  THEN
    RAISE EXCEPTION 'illegal mandate state transition';
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION reject_mandate_delete()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'mandate versions are immutable';
END;
$$;

CREATE OR REPLACE FUNCTION reject_order_snapshot_update()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF ROW(
    NEW.id, NEW.buyer_organization_id, NEW.supplier_organization_id,
    NEW.requester_subject, NEW.mandate_id, NEW.mandate_version,
    NEW.mandate_hash, NEW.catalog_item_id, NEW.catalog_item_version,
    NEW.sku, NEW.product_key, NEW.category, NEW.unit, NEW.unit_price,
    NEW.quantity, NEW.currency, NEW.total, NEW.delivery_location_id,
    NEW.policy_decision, NEW.policy_reasons_json, NEW.idempotency_key,
    NEW.request_hash, NEW.approval_expires_at, NEW.created_at
  ) IS DISTINCT FROM ROW(
    OLD.id, OLD.buyer_organization_id, OLD.supplier_organization_id,
    OLD.requester_subject, OLD.mandate_id, OLD.mandate_version,
    OLD.mandate_hash, OLD.catalog_item_id, OLD.catalog_item_version,
    OLD.sku, OLD.product_key, OLD.category, OLD.unit, OLD.unit_price,
    OLD.quantity, OLD.currency, OLD.total, OLD.delivery_location_id,
    OLD.policy_decision, OLD.policy_reasons_json, OLD.idempotency_key,
    OLD.request_hash, OLD.approval_expires_at, OLD.created_at
  ) THEN
    RAISE EXCEPTION 'order snapshot is immutable';
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION reject_audit_change()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'audit_events are append-only';
END;
$$;

DROP TRIGGER IF EXISTS mandates_guard_update ON mandates;
CREATE TRIGGER mandates_guard_update
  BEFORE UPDATE ON mandates
  FOR EACH ROW EXECUTE FUNCTION reject_mandate_immutable_update();

DROP TRIGGER IF EXISTS mandates_guard_delete ON mandates;
CREATE TRIGGER mandates_guard_delete
  BEFORE DELETE ON mandates
  FOR EACH ROW EXECUTE FUNCTION reject_mandate_delete();

DROP TRIGGER IF EXISTS orders_guard_snapshot ON orders;
CREATE TRIGGER orders_guard_snapshot
  BEFORE UPDATE ON orders
  FOR EACH ROW EXECUTE FUNCTION reject_order_snapshot_update();

DROP TRIGGER IF EXISTS audit_events_guard_update ON audit_events;
CREATE TRIGGER audit_events_guard_update
  BEFORE UPDATE ON audit_events
  FOR EACH ROW EXECUTE FUNCTION reject_audit_change();

DROP TRIGGER IF EXISTS audit_events_guard_delete ON audit_events;
CREATE TRIGGER audit_events_guard_delete
  BEFORE DELETE ON audit_events
  FOR EACH ROW EXECUTE FUNCTION reject_audit_change();
